sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  matrix:
    - DJANGO_VERSION="Django<1.9"
    - DJANGO_VERSION="Django<1.10"
    - DJANGO_VERSION="Django<1.11"
    - DJANGO_VERSION="--pre Django<2.1"
    - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install 'coverage<4' # coverage>=4 has issues with python3
  - pip install -q $DJANGO_VERSION
  - pip install -q coveralls
  - pip install -r requirements.txt

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION="Django<1.10"
    - python: "3.3"
      env: DJANGO_VERSION="Django<1.11"
    - python: "2.7"
      env: DJANGO_VERSION="--pre Django<2.1"
    - python: "3.3"
      env: DJANGO_VERSION="--pre Django<2.1"
    - python: "2.7"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.3"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.4"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

script:
    - django-admin --version
    - python -Wall $VIRTUAL_ENV/bin/coverage run setup.py test

after_success:
    - coveralls
